name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_job:
    runs-on: windows-latest
    name: Build Job
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install DocFX
        run: dotnet tool update -g docfx
        env:
          CI: true
      - name: build Documentation
        id: build-documentation
        run: |
          docfx build --warningsAsErrors
        shell: powershell
      - name: Zip artifact for deployment
        run: Compress-Archive -Path _site/* -DestinationPath .\_site.zip
      - name: Publish results
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: _site.zip
          
  deploy_job:
    if: (github.event_name == 'push' && github.repository == 'SkylineCommunications/dataminer-docs-connectors')
    runs-on: ubuntu-latest
    needs: build_job
    name: Deploy Job
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release
          path: .
      - name: Unzip artifact for deployment
        run: Expand-Archive -Path _site.zip -DestinationPath ./_site
        shell: pwsh
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_DUNE_071CBEE03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/_site" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
